[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = """
source ~/.config/nvim/plugins/denite.rc.vim
"""

[[plugins]]
repo = 'rcmdnk/vim-markdown'
on_ft = ['md', 'markdown']

[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']

[[plugins]]        
repo = 'prabirshrestha/asyncomplete.vim'    
on_ft = ['python', 'javascript', 'typescript']                     
    
[[plugins]] 
repo = 'prabirshrestha/async.vim'
on_ft = ['python', 'javascript', 'typescript']                     
                          
[[plugins]]
repo = 'prabirshrestha/vim-lsp'
on_ft = ['python', 'javascript', 'typescript']                     
depends = ['async.vim', 'vim-virtualenv']
hook_source = '''                                
source ~/.config/nvim/plugins/vim-lsp.rc.vim    
'''    
           
[[plugins]]
repo = 'ryanolsonx/vim-lsp-python'
on_ft = ['python']                        
depends = ['vim-lsp']     
                             
[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'
on_ft = ['python', 'javascript', 'typescript']                     

